name: CI Ruff

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:  

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v5

      - name: Lint con Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --fix"

      - name: Verificar formato (sin reescribir)
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check ."
